---
abstract: 'A comprehensive plugin system.'
author:
  - 'Aran Deltac <bluefeet@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
  File::Spec: '0'
  Test::More: '0'
  Test::Simple: '0.96'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.047, CPAN::Meta::Converter version 2.150001'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: MooX-PluginKit
requires:
  Carp: '0'
  Exporter: '0'
  Module::Runtime: '0.014'
  Moo: '2'
  Scalar::Util: '0'
  Type::Tiny: '1.000005'
  namespace::clean: '0.24'
  strictures: '2'
version: '0.01'
